python /kaggle/working/Chatbot_multi_turn/src/main.py \
    --seed=0 \
    --mode="infer" \
    --data_dir="/kaggle/working/data" \
    --model_type="gpt2" \
    --bos_token="<bos>" \
    --sp1_token="<sp1>" \
    --sp2_token="<sp2>" \
    --gpu="0" \
    --max_len=1024 \
    --max_turns=5 \
    --top_p=0.8 \
    --ckpt_dir="/kaggle/working/saved_models" \
    --ckpt_name="best_ckpt_epoch=1_valid_loss=2.8172" \
    --end_command="Abort!"
